version: CI Build {Build}
skip_commits:
  files:
  - '.github/**/*'
  - 'Website/**/*'
  - 'Scripts/**/*'
  - '*.md'
image: Visual Studio 2019
install:
  - >-
    git submodule update --init --recursive
build_script:
- cmd: >-
    dotnet nuget locals all --clear

    src\Native\BuildAllTargets.cmd

    7z a -r NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip ^
        .\src\Native\Output\*.exe ^
        .\src\Native\Output\*.dll ^
        .\src\Native\Output\*.pdb ^
        .\src\Native\Output\*.json
artifacts:
  - path: NSudo_CI_Build_%APPVEYOR_BUILD_NUMBER%.zip
