name: Git Mirror Action

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: 'master'
          persist-credentials: false
          fetch-depth: 0

      - run: |
          date > generated.txt
          git remote add gitee https://gitee.com/M2-Team/NSudo.git
          git fetch -q --all
          git push -q https://Mouri_Naruto:${{ secrets.GITEE_TOKEN }}@gitee.com/M2-Team/NSudo.git master --tags
